Changed optional dependency
Problem:
2014-08-16 21:16:00 [Server thread][WARN] [BombArena] Task #109 for
BombArena v1.2.0-SNAPSHOT generated an exception
java.lang.NoSuchMethodError:
com.gmail.filoghost.holograms
                   .api.Hologram.teleport(Lorg/bukkit/Location;)V
   mc.euro.demolition.holograms.HologramsOn.teleport(HologramsOn.java:38)~[?:?]
   mc.euro.demolition.BombArena$1.run(BombArena.java:326)~[?:?]

HolographicDisplays is an optional dependency, but if servers want to use
it, then they must use v1.8.5 or greater because these have the
Hologram.teleport() method.