Tested on older versions of BattleArena.
Updated the comments to reflect what is currently hindering full backwards
compatibility.

It turns out to be onBombCarrierLeave() line 266
getTimedSpawns.get(1L).spawn();

Specifically .spawn() from Spawnable().

Older versions return int.
Newer versions return void.

At runtime, this line produces a NoSuchMethodError

eventho the method is there... it just has a different return type.