Fixed negative timer caused by Exception
[18:36:03] [Server thread/WARN]: [BombArena] Task #10837 for BombArena
v1.2.2 generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between
WarSpawn and HWHeights
at org.bukkit.Location.distanceSquared(Location.java:456)
at org.bukkit.Location.distance(Location.java:439)
at mc.euro.demolition.timers.DetonationTimer.killPlayers(DetonationTimer.java:103)
at mc.euro.demolition.timers.DetonationTimer.createExplosion(DetonationTimer.java:97)
at mc.euro.demolition.timers.DetonationTimer.run(DetonationTimer.java:55)

The problem was that the player lost all their lives and was teleported
back to the "spawn area" (WarSpawn) while the match was going on in
another world (HWHeights in this case).

Apparently, getMatch().getPlayers() contains "dead" players (which might
be located in another world). So my initial assumption that getPlayers()
would be in the same world was wrong.

The fix is on line 103: Where I check the player's World against the
Match's World. As a further precaution, cancel() is now the first thing
executed when the timer reaches zero... This should prevent all further
negative timer bugs.

Because previously, cancel() was executed last... Therefore, any exception
could potentially skip cancel() and cause a negative timer bug.